name: Test and Build
on: 
    pull_request:
        branches: 
        #run when a pr is made (target must be master branch)
        - master
jobs:
    test-and-build:
        runs-on: ubuntu-latest    
        steps:
        - uses: actions/checkout@v1
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.201
        - name: Test/Build with dotnet
          env:
              MSBUILDDISABLENODEREUSE: 1
          run: |
                  cp -rfv infrastructure/. ./docs/Append.AntDesign.Documentation.Standalone/wwwroot
                  dotnet test
                  dotnet build